<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
    <Version>1.0.0</Version>
    <Authors>Devvio</Authors>
    <Product>Devvio Archiver</Product>
    <Copyright>Copyright © Devvio 2026</Copyright>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
