<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Devvio.Archiver.Shell</RootNamespace>
    <AssemblyName>DevvioArchiver.Shell</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpShell" Version="2.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevvioArchiver.Core\DevvioArchiver.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

</Project>
